export const ActionTypes = {
  //kigdom builder - pledgers map
  SET_BUILDERS_LIST: "SET_BUILDERS_LIST",
  FETCH_KINGDOM_BUILDERS_LIST: "FETCH_KINGDOM_BUILDERS_LIST",
  FETCH_KINGDOM_BUILDERS_LIST_SUCCESS: "FETCH_KINGDOM_BUILDERS_LIST_SUCCESS",
  FETCH_KINGDOM_BUILDERS_LIST_FAILURE: "FETCH_KINGDOM_BUILDERS_LIST_FAILURE",

  FETCH_KINGDOM_BUILDERS_COUNT: "FETCH_KINGDOM_BUILDERS_COUNT",
  FETCH_KINGDOM_BUILDERS_COUNT_SUCCESS: "FETCH_KINGDOM_BUILDERS_COUNT_SUCCESS",
  FETCH_KINGDOM_BUILDERS_COUNT_FAILURE: "FETCH_KINGDOM_BUILDERS_COUNT_FAILURE",

  FETCH_ZONAL_PLEDGERS_COUNT: "FETCH_ZONAL_PLEDGERS_COUNT",
  FETCH_ZONAL_PLEDGERS_COUNT_SUCCESS: "FETCH_ZONAL_PLEDGERS_COUNT_SUCCESS",
  FETCH_ZONAL_PLEDGERS_COUNT_FAILURE: "FETCH_ZONAL_PLEDGERS_COUNT_FAILURE",

  FETCH_PAYMENT_BREAKDOWN_COUNT: "FETCH_PAYMENT_BREAKDOWN_COUNT",
  FETCH_PAYMENT_BREAKDOWN_COUNT_SUCCESS: "FETCH_PAYMENT_BREAKDOWN_COUNT_SUCCESS",
  FETCH_PAYMENT_BREAKDOWN_COUNT_FAILURE: "FETCH_PAYMENT_BREAKDOWN_COUNT_FAILURE",

  FETCH_PLEDGER_TOTAL_AMOUNT_PAID: "FETCH_PLEDGER_TOTAL_AMOUNT_PAID",
  FETCH_PLEDGER_TOTAL_AMOUNT_PAID_SUCCESS: "FETCH_PLEDGER_TOTAL_AMOUNT_PAID_SUCCESS",
  FETCH_PLEDGER_TOTAL_AMOUNT_PAID_FAILURE: "FETCH_PLEDGER_TOTAL_AMOUNT_PAID_FAILURE",

  FETCH_PLEDGER_PAYMENT_DETAILS_BY_ID: "FETCH_PLEDGER_PAYMENT_DETAILS_BY_ID",
  FETCH_PLEDGER_PAYMENT_DETAILS_BY_ID_SUCCESS: "FETCH_PLEDGER_PAYMENT_DETAILS_BY_ID_SUCCESS",
  FETCH_PLEDGER_PAYMENT_DETAILS_BY_ID_FAILURE: "FETCH_PLEDGER_PAYMENT_DETAILS_BY_ID_FAILURE",

  //account map
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  CREATE_ACCOUNT_SUCCESS: "CREATE_ACCOUNT_SUCCESS",
  CREATE_ACCOUNT_FAILURE: "CREATE_ACCOUNT_FAILURE",

  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT: "LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  PASSWORD_RESET: "PASSWORD_RESET",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  PASSWORD_RESET_FAILURE: "PASSWORD_RESET_FAILURE",

  PASSWORD_UPDATE: "PASSWORD_UPDATE",
  PASSWORD_UPDATE_SUCCESS: "PASSWORD_UPDATE_SUCCESS",
  PASSWORD_UPDATE_FAILURE: "PASSWORD_UPDATE_FAILURE",

  GET_ACCOUNT: "GET_ACCOUNT",
};
