export const ActionTypes = {
  SET_BUILDERS_LIST: "SET_BUILDERS_LIST",
  FETCH_KINGDOM_BUILDERS_LIST: "FETCH_KINGDOM_BUILDERS_LIST",
  FETCH_KINGDOM_BUILDERS_LIST_FAILED: "FETCH_KINGDOM_BUILDERS_LIST_FAILED",
  USER_LOGIN: "USER_LOGIN",
};
