export const ActionTypes = {
  //kigdom builder - pledgers map
  SET_BUILDERS_LIST: "SET_BUILDERS_LIST",
  FETCH_KINGDOM_BUILDERS_LIST: "FETCH_KINGDOM_BUILDERS_LIST",
  FETCH_KINGDOM_BUILDERS_LIST_SUCCESS: "FETCH_KINGDOM_BUILDERS_LIST_SUCCESS",
  FETCH_KINGDOM_BUILDERS_LIST_FAILURE: "FETCH_KINGDOM_BUILDERS_LIST_FAILURE",

  //account map
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  CREATE_ACCOUNT_SUCCESS: "CREATE_ACCOUNT_SUCCESS",
  CREATE_ACCOUNT_FAILURE: "CREATE_ACCOUNT_FAILURE",
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  PASSWORD_RESET: "PASSWORD_RESET",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  PASSWORD_RESET_FAILURE: "PASSWORD_RESET_FAILURE",
  PASSWORD_UPDATE: "PASSWORD_UPDATE",
  PASSWORD_UPDATE_SUCCESS: "PASSWORD_UPDATE_SUCCESS",
  PASSWORD_UPDATE_FAILURE: "PASSWORD_UPDATE_FAILURE",
  GET_ACCOUNT: "GET_ACCOUNT",
};
